version: "3.8"

services:
  stream:
    image: stream:1.0
    container_name: stream
    ports:
    - 9090:9090
    restart: on-failure
    networks:
      - stream-mongo
    depends_on:
      - mongo-db
    links:
      - mongo-db
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
    - 27017:27017
    networks:
    - stream-mongo
    volumes:
    - 'mongodata:/data/db'
    - './init_scripts:/docker-entrypoint-initdb.d'
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=14292
    restart: unless-stopped

networks:
  stream-mongo:

volumes:
  mongodata: